DROP TABLE IF EXISTS courses;
DROP TABLE IF EXISTS professors;
DROP TABLE IF EXISTS students;
DROP SEQUENCE IF EXISTS global_seq;

CREATE SEQUENCE global_seq START WITH 100000;

CREATE TABLE professors
(
    id              INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
    name            VARCHAR(255)    NOT NULL,
    address         VARCHAR(255)    NOT NULL,
    phone           VARCHAR(10)     NOT NULL,
    payment         FLOAT           NOT NULL,
    course_id       INTEGER         NOT NULL
);

CREATE TABLE courses
(
    id              INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
    name            VARCHAR(255)    NOT NULL,
    number          INTEGER         NOT NULL,
    price           FLOAT           NOT NULL,
    professor_id    INTEGER
);

CREATE TABLE professor_course
(
    professor_id    INTEGER NOT NULL,
    course_id       INTEGER NOT NULL
);

