package ru.sorochinsky.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import ru.sorochinsky.model.Course;
import ru.sorochinsky.model.CourseProgress;
import ru.sorochinsky.repositiry.CourseProgressRepository;

import java.util.List;
import java.util.Map;

/**
 * Controller for {@link ru.sorochinsky.model.CourseProgress}'s pages.
 *
 * @author Ivan Sorochinsky
 * @version 1.0
 */

@Controller    // This means that this class is a Controller
@RequestMapping(path="/course_progress_controller") // This means URL's start with /course_progress_controller (after Application path)
public class CourseProgressController {
//    @Autowired // This means to get the bean called studentRepository
//    // Which is auto-generated by Spring, we will use it to handle the data
//    private CourseProgressRepository courseProgressRepository;
//
//    @PostMapping(path = "/progress") // Map ONLY POST Requests
//    public String add(@RequestParam List<Integer> points, Map<String, Object> model){
//
//        // @ResponseBody means the returned String is the response, not a view name
//        // @RequestParam means it is a parameter from the GET or POST request
//
//        CourseProgress n = new CourseProgress();
//        n.setPoints(points);
////          добавить поверку полей на NotNull
//        courseProgressRepository.save();
//        Iterable<CourseProgress> points = courseProgressRepository.findAll();
//        model.put("points", points);
//        return "points";
//    }
//
//    @GetMapping(path = "/progress")
//    public String progress(Map<String, Object> model){
//        Iterable<CourseProgress> points = courseProgressRepository.findAll();
//        model.put("points", points);
//        return "points";
//    }
}