package ru.sorochinsky.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import ru.sorochinsky.model.Professor;
import ru.sorochinsky.repositiry.ProfessorRepository;

import java.util.Map;

/**
 * Controller for {@link ru.sorochinsky.model.Professor}'s pages.
 *
 * @author Ivan Sorochinsky
 * @version 1.0
 */

@Controller    // This means that this class is a Controller
@RequestMapping(path="/course_controller") // This means URL's start with /course_controller (after Application path)
public class ProfessorController {
    @Autowired // This means to get the bean called courseRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private ProfessorRepository professorRepository;
    @PostMapping(path = "/professor") // Map ONLY POST Requests
    public String add(@RequestParam String name, @RequestParam String address
            , @RequestParam String phone, @RequestParam Float payment, Map<String, Object> model){

        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        Professor n = new Professor();
        n.setName(name);
        n.setAddress(address);
        n.setPhone(phone);
        n.setPayment(payment);
//          добавить поверку полей на NotNull
        professorRepository.save(n);
        Iterable<Professor> professorIterable = professorRepository.findAll();
        model.put("prof", professorIterable);
        return "prof";
    }

    @GetMapping(path = "/professor")
    public String curs(Map<String, Object> model){
        Iterable<Professor> professorIterable = professorRepository.findAll();
        model.put("prof", professorIterable);
        return "prof";
    }
}