GET http://127.0.0.1:8080/university/api/v1/course/count

###
GET http://127.0.0.1:8080/university/api/v1/course/

###
GET http://127.0.0.1:8080/university/api/v1/course/5

###
DELETE http://127.0.0.1:8080/university/api/v1/course/9

###
POST http://127.0.0.1:8080/university/api/v1/course/
Content-Type: application/json

{
  "cost": 500.0,
  "name": "Английский2",
  "number": 7777
}

###
PUT http://localhost:8080/university/api/v1/course/
Content-Type: application/json

{
  "cost": 700.0,
  "id": 7,
  "name": "Английский",
  "number": 777,
  "professors": [],
  "students": []
}







