GET http://127.0.0.1:8080/university/api/v1/professor/count
###
GET http://127.0.0.1:8080/university/api/v1/professor/
###
GET http://127.0.0.1:8080/university/api/v1/professor/1
###
DELETE http://127.0.0.1:8080/university/api/v1/professor/3
###
POST http://127.0.0.1:8080/university/api/v1/professor/
Content-Type: application/json

{
  "address": "Василево 23",
  "course": [],
  "name": "Курчатов В.П.",
  "payment": 2000.0,
  "phone": "8800253256"
}

###
PUT http://localhost:8080/university/api/v1/professor/
Content-Type: application/json

{
  "id": 4,
  "address": "Василево 23",
  "course": [],
  "name": "Курчатов Ф.П.",
  "payment": 2000.0,
  "phone": "8800253256"
}

