GET http://127.0.0.1:8080/university/api/v1/student/count
###
GET http://127.0.0.1:8080/university/api/v1/student/
###
GET http://127.0.0.1:8080/university/api/v1/student/1
###
DELETE http://127.0.0.1:8080/university/api/v1/student/4
###
POST http://127.0.0.1:8080/university/api/v1/student/new
Content-Type: application/json

{
  "address": "Василевичес 20 кв 43",
  "email": "ya3@yar.ru",
  "name": "Рихард Зорге",
  "phone": "+79787878755",
  "progress": 0.0,
  "recordBook": 667
}

###
PUT http://localhost:8080/university/api/v1/student/
Content-Type: application/json

{
  "id": 5,
  "address": "Василевичес 28 кв 43",
  "email": "ya3@yar.ru",
  "name": "Рихард Зорге",
  "phone": "+79787878755",
  "progress": 0.0,
  "recordBook": 667
}
###
POST http://127.0.0.1:8080/university/api/v1/student/add
Content-Type: application/json

{
  "course": {
    "id": 7
  },
  "student": {
    "id": 4
  }
}

