GET http://127.0.0.1:8080/university/api/v1/student/count
###
GET http://127.0.0.1:8080/university/api/v1/student/
###
GET http://127.0.0.1:8080/university/api/v1/student/4
###
DELETE http://127.0.0.1:8080/university/api/v1/student/5
###
POST http://127.0.0.1:8080/university/api/v1/student/
Content-Type: application/json

{
  "address": "Фрунзе 45",
  "email": "ya3@ya.ru",
  "name": "Иванов Иван",
  "phone": "+79787549395",
  "recordBook": 565658
}

###
PUT http://localhost:8080/university/api/v1/student/
Content-Type: application/json

{
  "id" : 4,
  "address": "Фрунзе 45",
  "email": "ya2@ya.ru",
  "name": "Иванов Иван",
  "phone": "+79787549394",
  "recordBook": 565657
}

