GET http://127.0.0.1:8080/university/api/v1/course/count

###
GET http://127.0.0.1:8080/university/api/v1/course/

###
GET http://127.0.0.1:8080/university/api/v1/course/5

###
DELETE http://127.0.0.1:8080/university/api/v1/course/10

###
POST http://127.0.0.1:8080/university/api/v1/course/
Content-Type: application/json

{
  "cost": 500.0,
  "name": "Английский2",
  "number": 7777
}

###
PUT http://localhost:8080/university/api/v1/course/
Content-Type: application/json

{
  "cost": 700.0,
  "id": 7,
  "name": "Английский",
  "number": 777,
  "professors": [],
  "students": []
}

###
POST http://127.0.0.1:8080/university/api/v1/course/add
Content-Type: application/json

{
  "course": {
    "id": 7
  },
  "student": {
    "id": 4
  }
}

###
DELETE http://127.0.0.1:8080/university/api/v1/course/delete_st
Content-Type: application/json

{
  "course": {
    "id": 7
  },
  "student": {
    "id": 4
  }
}






